name: Java Project CI 

on: 
  # [push, pull_request]: #does not wokr on branches
  push:   
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build: #job name

    runs-on: ubuntu-latest #runner uses a vm of its own

    steps:
    - uses: actions/checkout@V3
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with: 
        java-version: 17

    - name: Compile Java Files
      run: javac -cp "lib/*" -d bin src/apiData/**/*.java src/apiData/*.java

    - name: Run Java Class File
      run: java -cp "bin:lib/*" apiData.MainApp

  #test: 
